#!/bin/bash
echo "trabalhando com frontend" ;
cd /home/bruno/source/frontendDEV/PaintballSocialNetwork/;
git config credential.helper store;
git add . ;
git commit -m "$1" .;
git push;


echo "trabalhando com  AuthDEV";
cd /home/bruno/source/AuthDEV/PaintballSocialNetwork-AuthAPI/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;



echo "trabalhando com  ChampionshipDEV";
cd /home/bruno/source/ChampionshipDEV/PaintballSocialNetwork-Championship/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;


echo "trabalhando com  PlayersDEV";
cd /home/bruno/source/PlayersDEV/PaintballSocialNetwork-Players/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;




echo "trabalhando com  RabbitDEV";
cd /home/bruno/source/rabbitmq/PaintballSocialNetwork-Images/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;


echo "trabalhando com  rest-api";
cd /home/bruno/source/rest-api/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;


echo "trabalhando com  classbd";
cd /home/bruno/source/classbd/;
git config credential.helper store;
git 
git add . ;
git commit -m "$1" .;
git push;


